name: dagger
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: call dagger test function
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          args: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
